### ISSUE TITLE
Request alc295 

### ISSUE THREAD

**Issue by noeyesee1** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#40] opened 2018-01-21 09:56 UTC
Appreciated very much if there will be kext for ALC295
Thanks
[codec_dump0.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1649657/codec_dump0.txt)

**Comment by insanelydeepak** [comment] 2018-01-22 16:29
Hi
OSX version ?

**Comment by noeyesee1** [comment] 2018-01-23 03:44
Hi, 

OSX version is 10.13.2
thanks

**Comment by insanelydeepak** [comment] 2018-01-23 06:03
try this
[AppleHDA-280.12-ALC295.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654729/AppleHDA-280.12-ALC295.zip)

**Comment by noeyesee1** [comment] 2018-01-25 06:53
Thanks very much. Tried, but reboot. Thanks anyway

**Comment by lolitsgab** [comment] 2018-07-12 04:32
@insanelydeepak  This partially works, and must have HDAEnabler.kext installed to work (manually putting the layout-id to 13 still does not make the computer recognize the audio devices).

The issue is that only half the speakers work, and the main speaker (the one on top of the keyboard) does not work. Would you know how to fix this?

**Comment by insanelydeepak** [comment] 2018-07-23 07:06
Hi 
repo for 10.13 is created and i will take all 10.13 issue there actively 
please close this issue and open one  here 
[https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/tree/master](url)

**Closed** 2018-07-23 07:08 UTC
Labels: enhancement, help wanted
