### ISSUE TITLE
help] ALC 230  SOUND NO 

### ISSUE THREAD

**Issue by wolflonezx11** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#42] opened 2018-01-30 11:52 UTC
HI  

10.13.3  High Sierra 
LENOVO IEDAPAD 320-15 

ALC 230  

HELP ME

**Comment by insanelydeepak** [comment] 2018-02-03 09:53
Hi 
whats your issue ?

**Comment by wolflonezx11** [comment] 2018-02-05 23:52
No analog speaker sound. Please add.



​

2018-02-03 18:53 GMT+09:00 InsanelyDeepak <notifications@github.com>:

**Comment by insanelydeepak** [comment] 2018-02-06 04:30
provide these files

**Comment by wolflonezx11** [comment] 2018-02-06 19:14
ALC 230  PLZ



2018-02-06 13:30 GMT+09:00 InsanelyDeepak <notifications@github.com>:

**Comment by wolflonezx11** [comment] 2018-02-06 19:17
2018-02-07 4:14 GMT+09:00 김경석 <wolflonezx11@gmail.com>:

**Comment by insanelydeepak** [comment] 2018-02-07 12:09
Hi 
can you provide codec dump ? so we can add it

**Comment by wolflonezx11** [comment] 2018-02-10 20:59
[ALC230_HELPME.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1713746/ALC230_HELPME.zip)

**Comment by insanelydeepak** [comment] 2018-02-11 09:33
Hi 
i think you dont understand what i need 


` 1. Use Ubuntu or Any Version of Linux Distro (Note : Use the latest version of Linux and Alsa drivers )
 2. Open Terminal and copy paste below Code :
  ~/Desktop && mkdir CodecDump && for c in /proc/asound/card*/codec#*; do f="${c/\/*card/card}"; cat "$c" > CodecDump/${f//\//-}.txt; done && zip -r CodecDump.zip CodecDump
  
 3. On Desktop there’s a folder/file name Codec_dump
 4. Save this to safe place  `

**Comment by damneq** [comment] 2018-02-11 11:51
I have the same device and I think that this is the file you're looking for: https://1drv.ms/t/s!AuIoHo29E-jL0Hafz7PHg1smmS8I

**Comment by insanelydeepak** [comment] 2018-02-21 15:30
Hi 
plz mention OSX version , so i can make progress

**Comment by wolflonezx11** [comment] 2018-02-22 13:26
Please.
Please add alc230 or
Please send me a patch file.

**Comment by insanelydeepak** [comment] 2018-02-22 17:44
OS version please ?

**Comment by wolflonezx11** [comment] 2018-02-22 23:07
iso 10.13.3 
plz

**Comment by insanelydeepak** [comment] 2018-02-23 18:10
try this , use layoutID = 13 

[AppleHDA-280.12-ALC230.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1752676/AppleHDA-280.12-ALC230.zip)

**Comment by korreckj328** [comment] 2018-03-05 23:47
I'm sorry,   I have the the same laptop with ALC230 and am having a hell of a time understanding what I need to do as it's my first hackintosh.  I installed the AppleHDA.kext you linked,  and then I patched my DSDT with this:

into method label _DSM parent_label HDEF remove_entry;
into device label HDEF insert
begin
Method (_DSM, 4, NotSerialized)\n
{\n
    If (LEqual (Arg2, Zero)) { Return (Buffer() { 0x03 } ) }\n
    Return (Package()\n
    {\n
        "layout-id", Buffer() { 12, 0x00, 0x00, 0x00 },\n
        "hda-gfx", Buffer() { "onboard-1" },\n
        "PinConfigurations", Buffer() { },\n
        //"MaximumBootBeepVolume", 77,\n
    })\n
}\n
end;

into method label _DSM parent_label HDAS remove_entry;
into device label HDAS insert
begin
Method (_DSM, 4, NotSerialized)\n
{\n
    If (LEqual (Arg2, Zero)) { Return (Buffer() { 0x03 } ) }\n
    Return (Package()\n
    {\n
        "layout-id", Buffer() { 13, 0x00, 0x00, 0x00 },\n
        "hda-gfx", Buffer() { "onboard-1" },\n
        "PinConfigurations", Buffer() { },\n
        //"MaximumBootBeepVolume", 77,\n
    })\n
}\n
end;

Sound is the last thing I have to get running and I'm beating my head into a wall trying to understand it.

**Comment by insanelydeepak** [comment] 2018-03-06 04:06
this is correct , just install kext and restart to see result

**Comment by korreckj328** [comment] 2018-03-06 16:46
I was afraid of that.  I still don't have sound and when I run audio_detect_v2.3.command to look at if I have things right I get this output.  
[test.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1785845/test.txt)

**Comment by insanelydeepak** [comment] 2018-03-06 16:49
need these files 

https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by korreckj328** [comment] 2018-03-06 18:07
Here are the files.  My system information screen doesn't look like it's what needs to be there,  so that's likely what the problem is.  I just have no idea of what mistake I'm making and I'm pretty sure it is my mistake.

[HDA_troubleshooting.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1786119/HDA_troubleshooting.zip)

**Comment by insanelydeepak** [comment] 2018-03-11 22:47
@felipe-alves-reis 

need these files
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by felipe-alves-reis** [comment] 2018-03-11 23:16
[info.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1800982/info.zip)
@insanelydeepak

**Comment by insanelydeepak** [comment] 2018-03-11 23:22
@felipe-alves-reis you have layout id 3  instead 13 , config.plist is good maybe you DSDT has 3 , kext patches are not required for above kexts

**Comment by insanelydeepak** [comment] 2018-03-11 23:24
@korreckj328 can you check any input/output in system pref => Sound

**Comment by felipe-alves-reis** [comment] 2018-03-11 23:42
@insanelydeepak I changed the layout id to 3 and removed the DSDT patches on the clover, rebooted and did not work.

**Comment by insanelydeepak** [comment] 2018-03-11 23:44
no you have to use 13 , but however your system is using 3 which means you have a dsdt which has layout 3 already there

**Comment by korreckj328** [comment] 2018-03-12 00:24
@insanelydeepak Nothing for anything internal,  I have options for airplay to some of my other devices,  and the bluetooth sound bar I use at the moment but that's it.  
![output](https://user-images.githubusercontent.com/34418527/37260496-35225ad4-256a-11e8-818a-704d00155e7a.png)
![input](https://user-images.githubusercontent.com/34418527/37260497-37aa324a-256a-11e8-98ee-13b340391273.png)

**Comment by insanelydeepak** [comment] 2018-03-12 00:26
provide your clover folder i will look

**Comment by korreckj328** [comment] 2018-03-12 00:28
> provide your clover folder i will look

Me or Felipe?

**Comment by felipe-alves-reis** [comment] 2018-03-12 00:30
[info.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1801043/info.zip)
@insanelydeepak I removed the DSDT patch, i inject into clover 13 and it did not work. Could you see if I did everything right, please?

**Comment by felipe-alves-reis** [comment] 2018-03-12 11:44
Is it working for you? @korreckj328

**Comment by felipe-alves-reis** [comment] 2018-03-14 02:19
Could anyone help? :(

**Comment by korreckj328** [comment] 2018-03-14 02:52
Patience man.  You’re talking about a new patch for new hardware that the writers may not own,  and where the writer is doing this on their own time.

**Comment by insanelydeepak** [comment] 2018-03-14 04:01
Hi 
guys i was out of town for few days , will look on your reported files and get you back

**Comment by felipe-alves-reis** [comment] 2018-03-14 12:19
@insanelydeepak Sorry, I thought you two gave up.

**Comment by korreckj328** [comment] 2018-03-14 14:27
@felipe-alves-reis Not given up but out of my current skill set on this.  So I'm just waiting like you are.  While I've learned a lot during this hackintosh learning project,  my ability to write code myself is limited to just some basic CLI stuff with swift and python at the moment.

**Comment by insanelydeepak** [comment] 2018-03-14 17:23
@felipe-alves-reis  and @korreckj328  i never gave up 
I never ever owned a laptop, all laptop audio files are from user who requested and help to create it , if somehow user delays in help this got delayed , you can see there are many issue they open but never serious in help to fix it  

some codecs (ALC255) are hard to fix but atleast you have 80% audio input / output working 

so i always happy to help

**Comment by felipe-alves-reis** [comment] 2018-03-14 17:33
@insanelydeepak my codec is alc230 and I do not have any audio devices working, just missing this for my hackintosh to be 100% functional.

**Comment by insanelydeepak** [comment] 2018-03-14 17:35
@felipe-alves-reis 
[files.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1812277/files.zip)

try this files and can you provide raw DSDT (non- patched one )

**Comment by insanelydeepak** [comment] 2018-03-14 17:36
@felipe-alves-reis 

> my codec is alc230 and I do not have any audio devices working, just missing this for my hackintosh to be 100% functional.

above was example for codec ALC255 every laptop has it own issue but still 80% audio works

**Comment by felipe-alves-reis** [comment] 2018-03-14 17:43
@insanelydeepak When I leave work I will try to start the laptop with the files you sent me. Are you requesting that I send you my raw DSDT? Sorry, I did not understand the last part, my English is not very good.

**Comment by insanelydeepak** [comment] 2018-03-14 17:45
@felipe-alves-reis take your time 

Raw DSDT = look into Clover/ACPI/Origin folder  provide me 

if folder is empty  then goto clover boot menu and press f4 , then get to folder again

**Comment by korreckj328** [comment] 2018-03-14 18:46
[origin.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1812572/origin.zip)

**Comment by korreckj328** [comment] 2018-03-14 18:52
I'll try the files out when I have a chance.  Right now I'm dealing a "other people's problems" have become "my emergency" situation so it may take a few days before I have time to tinker with it again.  I zipped up my dsdt origin folder from EFI for you though so that you have that to look at if needed.

**Comment by felipe-alves-reis** [comment] 2018-03-14 23:02
Hi, I got home and started the notebook with the files that you sent me and it did not work. Follow the folder you requested.
[origin.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1813428/origin.zip)

**Comment by korreckj328** [comment] 2018-03-15 22:34
@insanelydeepak 

What should the system profiler say under audio with your patch?  
My sound doesn't work but either something I tried just got things to load up a little or Toast installed something called soundflower when I installed it and I'm trying to figure out if it's from your patch or toast.  
![screen shot 2018-03-15 at 6 33 52 pm](https://user-images.githubusercontent.com/34418527/37494500-7bb6663a-287f-11e8-8f20-2e4bc4296537.png)

**Comment by felipe-alves-reis** [comment] 2018-03-16 01:07
@korreckj328 I believe it is not his patch, because mine did not appear.

**Comment by insanelydeepak** [comment] 2018-03-16 03:53
Hi 
@korreckj328 this is normal 
it seems you have OSX 10.12.x ? right 

@felipe-alves-reis i check your files and found patch DSDT don't have HDEF or HDAS device, but original DSDT has , thats why it was not working for you 

i want you to apply all patches to origin DSDT and send it to me so i can be sure

**Comment by insanelydeepak** [comment] 2018-03-16 03:54
im going to start from scratch for you both , 
again you both OSX Version and send DSDT + Config.plist

**Comment by felipe-alves-reis** [comment] 2018-03-16 13:05
@insanelydeepak 
In DSDT I had the id 3, I changed it to 13, but it did not work, so I deleted this HDEF patch where the device appeared and injected the id 13 with the clover.

Let's see if I understood, is it to redo this patch HDEF with id 13, keep my config.plist and restart the laptop or is it to use the config.plist that you previously sent?

**Comment by korreckj328** [comment] 2018-03-16 14:59
@insanelydeepak 
/facepalm nope theres my problem.  I'm running 10.13.3. Didn't read close enough to notice that this was for Sierra not High Sierra.

**Comment by felipe-alves-reis** [comment] 2018-03-17 03:15
@insanelydeepak

Mac OS Version: 10.13.3

[DSDT and Config plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1821213/DSDT.and.Config.plist.zip)

**Comment by insanelydeepak** [comment] 2018-03-20 03:59
@felipe-alves-reis 
[Files .zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1827868/Files.zip)

try this

**Comment by felipe-alves-reis** [comment] 2018-03-20 23:51
@insanelydeepak Excellent, we have made progress, now identifies the headphones, the speaker and the hdmi audio are missing. 
![captura de tela 2018-03-20 as 20 45 34](https://user-images.githubusercontent.com/7799406/37688708-28425d92-2c80-11e8-8104-4efb83599018.png)

**Comment by insanelydeepak** [comment] 2018-03-21 18:03
great , so is headphone working ?  
plz provide me codec_dump

**Comment by felipe-alves-reis** [comment] 2018-03-21 20:16
@insanelydeepak Yes, when I get home, I send the codec_dump.

**Comment by korreckj328** [comment] 2018-03-21 23:46
Ok,  well I just finished dealing with some things and have time to tinker again.  Looks like Felipe has made way more progress than I.  I'm going to wipe and start fresh to make sure that none of the other stuff I've done to try to get audio are interfering.  I think I got it back to a vanilla applehda state before I started with this,  but just incase I didn't I'm going to make sure tonight.

**Comment by felipe-alves-reis** [comment] 2018-03-22 01:06
@insanelydeepak 
[codec_dump_alc230.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1835700/codec_dump_alc230.txt)
[codec_dump_hdmi.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1835701/codec_dump_hdmi.txt)

**Comment by korreckj328** [comment] 2018-03-23 01:13
[AppleHDA-280.12-ALC230.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1839758/AppleHDA-280.12-ALC230.zip)

Used This patched appleHDA and got it running tonight.  It uses layout-id 3 instead of 13 but I can confirm that it works for my alc230 for speakers,  headphones, and microphone on 10.13.3

**Comment by felipe-alves-reis** [comment] 2018-03-23 02:54
Great, now my speakers works with the @korreckj328  files, headphones do not work and do not appear in device list. @insanelydeepak 
![captura de tela 2018-03-22 as 23 54 07](https://user-images.githubusercontent.com/7799406/37809067-59ec70b4-2e2c-11e8-9518-4d7592c446fd.png)

**Comment by insanelydeepak** [comment] 2018-03-23 09:31
@korreckj328 great enjoy

**Comment by insanelydeepak** [comment] 2018-03-23 09:44
Hi plz try this layout 13 

@korreckj328 you also try share result will great help


[ALC230.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1840964/ALC230.zip)

**Comment by korreckj328** [comment] 2018-03-23 14:07
@insanelydeepak sure give me a couple days I might not get to it soon as I woke up this morning to a sick kid.

**Comment by insanelydeepak** [comment] 2018-03-23 14:11
@korreckj328 no hurry, take your time :)

**Comment by felipe-alves-reis** [comment] 2018-03-23 20:54
only v1 worked, only the speakers appeared, HDMI and headphones not recognize. V2 and v3 did not recognize any device.
@insanelydeepak

**Comment by insanelydeepak** [comment] 2018-03-24 01:41
this one

[ALC230.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1843937/ALC230.zip)

**Comment by felipe-alves-reis** [comment] 2018-03-26 13:36
Is this file you uploaded a new version of what you uploaded before?? @insanelydeepak.

The file I tested was from this comment below:
"Hi plz try this layout 13

@korreckj328 you also try share result will great help
@felipe-alves-reis try this one

ALC230.zip"

**Comment by felipe-alves-reis** [comment] 2018-03-26 13:36
Is this file you uploaded a new version of what you uploaded before?? @insanelydeepak.

The file I tested was from this comment below:
"Hi plz try this layout 13

@korreckj328 you also try share result will great help
@felipe-alves-reis try this one

ALC230.zip"

**Comment by felipe-alves-reis** [comment] 2018-03-27 00:12
The same thing happened, only v1 worked, only the speakers
@insanelydeepak

**Comment by llamorinjason** [comment] 2018-06-23 09:08
@felipe-alves-reis can you provide me your efi please? we have the same laptop im scratching my head because i cant make it work with speaker. I also dont know how to patch dsdt, what i know is just adding kext to the clover/other folder

**Comment by insanelydeepak** [comment] 2018-06-24 04:38
Hi 
i'm thinking to revisit and fix it , if anyone interested let me know 
otherwise i will close this issue

**Comment by oshahin** [comment] 2018-06-28 15:42
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2145956/Archive.zip)
i have alc 230 labtop 
my os is 11.14 
i attached my orign dsdt and clover confige and sound dump from linuxe 

would you please help with applehda patch ?

**Comment by anmoolpk** [comment] 2018-06-28 18:10
hi insanely Deepak my Lenovo ideated  320-14ikb  I used your ALC230 AppleHDA.kext to my system it worked on high Sierra and Mojave 10.14  but not worked on Sierra 10.12 please fix this compatibility 
I waiting your anwser and file

**Comment by insanelydeepak** [comment] 2018-07-23 07:08
Hi
repo for 10.13 is created and i will take all 10.13 issue there actively
please close this issue and open one below
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/issues

**Closed by insanelydeepak** 2018-07-23 07:08 UTC
Labels: enhancement
